// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BookingController from "./booking_controller"
application.register("booking", BookingController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideCustomerSliderController from "./hide_customer_slider_controller"
application.register("hide-customer-slider", HideCustomerSliderController)

import MapController from "./map_controller"
application.register("map", MapController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)
